### ISSUE TITLE
Analysis report 

### ISSUE THREAD

**Issue by chrisngan24** [chrisngan24/fydp#18]
point man for organizing the report

**Comment by joshuroy** [comment]
heuristics research for @clementfung:
-Nose/nostril relative to face is high indicator of orientation: http://www.aicit.org/AISS/ppl/03AISSVOL4NO5MAIN_part19.pdf, https://books.google.ca/books?id=FMdpBAAAQBAJ&pg=PA510&lpg=PA510&dq=image+recognition+head+turn&source=bl&ots=MKB2YrE96U&sig=xX8NYKzEBL3ae0ql6nabs-9Ti4c&hl=en&sa=X&ved=0CCIQ6AEwAWoVChMIpcn138r1yAIVyRkeCh03ggRh#v=onepage&q=image%20recognition%20head%20turn&f=false
-Eventually need to determine range of movement that corresponds to blind spot. These papers looks at cleaning bg and vector thresholds/predictions for head turning: http://media.cs.tsinghua.edu.cn/~windcat/paper/2007/icig07-dongligeng-headgesture.pdf, http://arxiv.org/ftp/arxiv/papers/1308/1308.0890.pdf, https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=27&cad=rja&uact=8&ved=0CDgQFjAGOBRqFQoTCMHMxPHS9cgCFckeHgodUl8EjA&url=http%3A%2F%2Fwww.irbis-nbuv.gov.ua%2Fcgi-bin%2Firbis_nbuv%2Fcgiirbis_64.exe%3FC21COM%3D2%26I21DBN%3DUJRN%26P21DBN%3DUJRN%26IMAGE_FILE_DOWNLOAD%3D1%26Image_file_name%3DPDF%2Foeiet_2009_1_7.pdf&usg=AFQjCNGYmew89uKONkJ7qjrc5W7PTlVXvg&sig2=XxGDbByQgUUy3ass5orNZQ&bvm=bv.106379543,d.dmo
-Can we train algo to find thresholds for highest information gain? Like this: http://eprints.maynoothuniversity.ie/2548/3/DK_Automatic_Recognition.pdf
-Haar-feature detection in OpenCV, but seems difficult to do during rotations: http://docs.opencv.org/master/d7/d8b/tutorial_py_face_detection.html#gsc.tab=0

Overall, seems easy to detect features but not a rotation to almost 90 deg? Halp Alex
